### PR TITLE
Depreciated Card Types [Complete]

### PR DESCRIPTION
**Pull request by VeXHarbinger**
Making sure all these changes are getting rolled into the checkin

### CODE REVIEW

**Comment by VeXHarbinger** [comment]
Ok, this time it looks as-if all the changes are in there for the removed card types.  Once we can merge this fully, I'll make the request for the branch with the test kits and Extended card types.  Then I can do the same for the enhanced Image object that includes the alt properties.

**Comment by VeXHarbinger** [comment]
Is this awaiting any additional changes from me?  I'd love to check this in so I can initiate the pull request from the other branch with the test kits

**Comment by RehanSaeed** [comment]
I'm just back from holiday. Will look at this as soon as I get through my post-holiday backlog.

**Comment by VeXHarbinger** [comment]
Any luck with this merge/pull? I'd love to get both of these merged in if we can so I can pick up with the next items I'd like to start on.

**Comment by RehanSaeed** [comment]
Reviewed it, looks fine except the CodeMaid.config and change to the .sln file but I'll clean that up.

**Comment by VeXHarbinger** [comment]
Oh so cool, Thank you.  I'll sync up my other fork with the test kits to master and issue a pull req on that one tonight.

**Comment by RehanSaeed** [comment]
This has been published to NuGet. Thanks for all your work.

**Comment by RehanSaeed** [comment]
Add you to the thank you section on the [home page](https://github.com/ASP-NET-MVC-Boilerplate/Templates).

**Pull request merged**
